// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HybridExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidHybridExtensionPackageString = "241793d1-e99d-460b-9b6e-02be07bb3d2e";
        public static Guid guidHybridExtensionPackage = new Guid(guidHybridExtensionPackageString);

        public const string guidHybridExtensionPackageCmdSetString = "4c75d764-d134-45c7-9e84-449bac425ba8";
        public static Guid guidHybridExtensionPackageCmdSet = new Guid(guidHybridExtensionPackageCmdSetString);

        public const string guidImagesString = "89b4ae10-5a3f-4f12-b50a-4d4101cd3f9f";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int VsSdkHelloWorldCommandId = 0x0100;
        public const int VsSdkMefReferenceCommandId = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
    }
}